apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-simple-app
  namespace: default
spec:
  type: Python
  mode: cluster
  image: spark-py:simple-app
  mainApplicationFile: local:///opt/spark/python/SimpleApp.py
  deps:
    jars:
    - local:///opt/spark/jars/hadoop-aws.jar
    - local:///opt/spark/jars/aws-java-sdk-bundle.jar
  driver:
    javaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    env:
    - name: S3_ENDPOINT
      value: https://minio.minio-tenant.svc.cluster.local
    - name: S3_ACCESS_KEY
      value: ePUcLOV4MWg83ZSLvR8z
    - name: S3_SECRET_KEY
      value: hvOtahI6KoaojcYB6Qe5IxVC1T2w8x3VvzYre0Rx
    - name: S3_BUCKET
      value: documents
    - name: S3_FILE_PATH
      value: README.md
    # cores: 1
    # coreLimit: "1200m"
    # memory: "512m"
    labels:
      version: 3.5.5
  executor:
    javaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    env:
    - name: S3_ENDPOINT
      value: https://minio.minio-tenant.svc.cluster.local
    - name: S3_ACCESS_KEY
      value: ePUcLOV4MWg83ZSLvR8z
    - name: S3_SECRET_KEY
      value: hvOtahI6KoaojcYB6Qe5IxVC1T2w8x3VvzYre0Rx
    - name: S3_BUCKET
      value: documents
    - name: S3_FILE_PATH
      value: README.md
    # cores: 1
    instances: 2
    # memory: "512m"
    labels:
      version: 3.5.5
  sparkVersion: "3.5.5"