apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-bucket-monitor-v2-app
  namespace: default
spec:
  type: Python
  mode: cluster
  image: spark-py:base-tls
  mainApplicationFile: https://minio.minio-tenant.svc.cluster.local/python/BucketMonitorApp-v2.py
  deps:
    jars:
    - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
    - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
  driver:
    env:
    - name: S3_ENDPOINT
      value: https://minio.minio-tenant.svc.cluster.local
    - name: S3_ACCESS_KEY
      value: ePUcLOV4MWg83ZSLvR8z
    - name: S3_SECRET_KEY
      value: hvOtahI6KoaojcYB6Qe5IxVC1T2w8x3VvzYre0Rx
    - name: S3_BUCKET
      value: documents
    # cores: 1
    # coreLimit: "1200m"
    # memory: "512m"
    labels:
      version: 3.5.5
  executor:
    env:
    - name: S3_ENDPOINT
      value: https://minio.minio-tenant.svc.cluster.local
    - name: S3_ACCESS_KEY
      value: ePUcLOV4MWg83ZSLvR8z
    - name: S3_SECRET_KEY
      value: hvOtahI6KoaojcYB6Qe5IxVC1T2w8x3VvzYre0Rx
    - name: S3_BUCKET
      value: documents
    # cores: 1
    instances: 2
    # memory: "512m"
    labels:
      version: 3.5.5
  sparkVersion: "3.5.5"
