apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-final-project-app
  namespace: default
spec:
  type: Python
  mode: cluster
  image: spark-py:base-tls
  mainApplicationFile: https://minio.minio-tenant.svc.cluster.local/python/FinalProjectApp.py
  deps:
    jars:
    # NEO4J
    - https://github.com/neo4j/neo4j-spark-connector/releases/download/5.3.5/neo4j-connector-apache-spark_2.12-5.3.5_for_spark_3.jar
  driver:
    env:
    # NEO4J
    - name: NEO4J_URL
      value: bolt://98.80.135.56
    - name: NEO4J_USERNAME
      value: neo4j
    - name: NEO4J_PASSWORD
      value: transactions-program-parties
    - name: NEO4J_DATABASE
      value: neo4j
    # cores: 1
    # coreLimit: "1200m"
    # memory: "512m"
    labels:
      version: 3.5.5
  executor:
    env:
    # NEO4J
    - name: NEO4J_URL
      value: bolt://98.80.135.56
    - name: NEO4J_USERNAME
      value: neo4j
    - name: NEO4J_PASSWORD
      value: transactions-program-parties
    - name: NEO4J_DATABASE
      value: neo4j
    # cores: 1
    instances: 2
    # memory: "512m"
    labels:
      version: 3.5.5
  sparkVersion: "3.5.5"
