apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-sample-app
  namespace: default
spec:
  type: Python
  mode: cluster
  image: apache/spark:3.5.5
  mainApplicationFile: local:///opt/spark/scripts/SampleApp.py
  deps:
    jars:
    - https://github.com/neo4j/neo4j-spark-connector/releases/download/5.3.5/neo4j-connector-apache-spark_2.12-5.3.5_for_spark_3.jar
  driver:
    volumeMounts:
    - name: app-volume
      mountPath: /opt/spark/scripts
    initContainers:
    - name: fetch-script
      image: curlimages/curl
      command:
        - sh
        - -c
        - 'curl -k -o /opt/spark/scripts/SampleApp.py https://minio.minio-tenant.svc.cluster.local/python/SampleApp.py'
      volumeMounts:
        - name: app-volume
          mountPath: /opt/spark/scripts
    # cores: 1
    # coreLimit: "1200m"
    # memory: "512m"
    labels:
      version: 3.5.5
  executor:
    volumeMounts:
    - name: app-volume
      mountPath: /opt/spark/scripts
    # cores: 1
    instances: 2
    # memory: "512m"
    labels:
      version: 3.5.5
  volumes:
  - name: app-volume
    emptyDir: {}
  sparkVersion: "3.5.5"